repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.79.1
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
    - id: terraform_validate
      args:
        - --hook-config=--retry-once-with-cleanup=true
    - id: terraform_tflint
    - id: terragrunt_fmt
    - id: terragrunt_validate
